version: '3'
services:
  
  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: habib/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-main/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8989:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./docker-main/nginx/:/etc/nginx/conf.d/
      - /etc/letsencrypt/live/baity-dev.baityapp.online/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/baity-dev.baityapp.online:/etc/nginx/ssl/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/ssl/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/nginx/ssl/ssl-dhparams.pem
    env_file: .env
    networks:
      - app-network
      
  redis:
    image: redis:6-alpine
    container_name: laravel_scaffold_cache
    ports:
      - "8002:6379"
    volumes:
      - cache_data:/data
    networks:
      - app-network
        
  #MySQL
  # db:
  #   image: mysql:5.7.22
  #   container_name: db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_DATABASE: laravel
  #     MYSQL_ROOT_PASSWORD: password
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql/
  #     - ./docker-main/mysql/:/etc/mysql/
  #   networks:
  #     - app-network

#Volumes
volumes:
  cache_data:
    driver: local

#Networks
networks:
  app-network:
    driver: bridge
