<?php

namespace App\Facades;

use Illuminate\Support\Facades\Facade;
use App\Contracts\MessengerProvider;
use App\Models\GhostUser;
use App\Models\Participant;

/**
 * @method static \App\Messenger setProvider($provider = null, bool $scoped = false)
 * @method static \App\Messenger setScopedProvider($provider = null)
 * @method static \App\Messenger unsetProvider(bool $scoped = false, bool $flush = false)
 * @method static \App\Messenger unsetScopedProvider()
 * @method static MessengerProvider|null getProvider(bool $withoutRelations = false)
 * @method static bool isProviderSet()
 * @method static bool isScopedProviderSet()
 * @method static bool isValidMessengerProvider($provider = null)
 * @method static string|null findProviderAlias($provider = null)
 * @method static MessengerProvider|string|null findAliasProvider(string $alias)
 * @method static bool isProviderSearchable($provider = null)
 * @method static bool isProviderFriendable($provider = null)
 * @method static bool isProvidersCached()
 * @method static \App\Messenger setConfig(array $params)
 * @method static array getConfig()
 * @method static array getSystemFeatures()
 * @method static array getAllSearchableProviders()
 * @method static array getAllFriendableProviders()
 * @method static array getAllProviders(bool $returnFullClass = false)
 * @method static array getRawProviders()
 * @method static array getAllProvidersWithDevices()
 * @method static int getMessageSizeLimit()
 * @method static \App\Messenger setMessageSizeLimit(int $messageSizeLimit)
 * @method static bool isKnockKnockEnabled()
 * @method static \App\Messenger setKnockKnock(bool $knockKnock)
 * @method static int getKnockTimeout()
 * @method static \App\Messenger setKnockTimeout(int $knockTimeout)
 * @method static \App\Messenger disableCallsTemporarily(int $minutesDisabled)
 * @method static bool isCallingTemporarilyDisabled()
 * @method static \App\Messenger removeTemporaryCallShutdown()
 * @method static bool isCallingEnabled()
 * @method static \App\Messenger setCalling(bool $calling)
 * @method static bool isBotsEnabled()
 * @method static \App\Messenger setBots(bool $bots)
 * @method static bool shouldVerifyPrivateThreadFriendship()
 * @method static \App\Messenger setVerifyPrivateThreadFriendship(bool $verifyPrivateThreadFriendship)
 * @method static bool shouldVerifyGroupThreadFriendship()
 * @method static \App\Messenger setVerifyGroupThreadFriendship(bool $verifyGroupThreadFriendship)
 * @method static bool isSystemMessagesEnabled()
 * @method static \App\Messenger setSystemMessages(bool $systemMessages)
 * @method static \App\Messenger setThreadInvites(bool $invites)
 * @method static bool isThreadInvitesEnabled()
 * @method static \App\Messenger setThreadInvitesMaxCount(int $maxInviteCount)
 * @method static int getThreadMaxInvitesCount()
 * @method static bool isMessageEditsEnabled()
 * @method static \App\Messenger setMessageEdits(bool $messageEdits)
 * @method static bool isMessageEditsViewEnabled()
 * @method static \App\Messenger setMessageEditsView(bool $messageEditsView)
 * @method static \App\Messenger setMessageReactions(bool $messageReactions)
 * @method static bool isMessageReactionsEnabled()
 * @method static int getMessageReactionsMax()
 * @method static \App\Messenger setMessageReactionsMax(int $messageReactionsMax)
 * @method static bool isMessageImageUploadEnabled()
 * @method static \App\Messenger setMessageImageUpload(bool $messageImageUpload)
 * @method static bool isProviderAvatarEnabled()
 * @method static \App\Messenger setProviderAvatars(bool $providerAvatars)
 * @method static bool isThreadAvatarEnabled()
 * @method static \App\Messenger setThreadAvatars(bool $threadAvatars)
 * @method static bool isBotAvatarEnabled()
 * @method static \App\Messenger setBotAvatars(bool $botAvatars)
 * @method static bool isMessageDocumentUploadEnabled()
 * @method static \App\Messenger setMessageDocumentUpload(bool $messageDocumentUpload)
 * @method static bool isOnlineStatusEnabled()
 * @method static \App\Messenger setOnlineStatus(bool $onlineStatus)
 * @method static int getOnlineCacheLifetime()
 * @method static \App\Messenger setOnlineCacheLifetime(int $onlineCacheLifetime)
 * @method static int getThreadsIndexCount()
 * @method static \App\Messenger setThreadsIndexCount(int $threadsIndexCount)
 * @method static int getSearchPageCount()
 * @method static \App\Messenger setSearchPageCount(int $searchPageCount)
 * @method static int getThreadsPageCount()
 * @method static \App\Messenger setThreadsPageCount(int $threadsPageCount)
 * @method static int getParticipantsIndexCount()
 * @method static \App\Messenger setParticipantsIndexCount(int $participantsIndexCount)
 * @method static int getParticipantsPageCount()
 * @method static \App\Messenger setParticipantsPageCount(int $participantsPageCount)
 * @method static int getMessagesIndexCount()
 * @method static \App\Messenger setMessagesIndexCount(int $messagesIndexCount)
 * @method static int getMessagesPageCount()
 * @method static \App\Messenger setMessagesPageCount(int $messagesPageCount)
 * @method static int getCallsIndexCount()
 * @method static \App\Messenger setCallsIndexCount(int $callsIndexCount)
 * @method static int getCallsPageCount()
 * @method static \App\Messenger setCallsPageCount(int $callsPageCount)
 * @method static array|string getAvatarStorage(string $config = null)
 * @method static array|string getThreadStorage(string $config = null)
 * @method static bool isPushNotificationsEnabled()
 * @method static \App\Messenger setPushNotifications(bool $pushNotifications)
 * @method static void setProviderToOnline($provider = null)
 * @method static void setProviderToOffline($provider = null)
 * @method static void setProviderToAway($provider = null)
 * @method static bool isProviderOnline($provider = null)
 * @method static bool isProviderAway($provider = null)
 * @method static int getProviderOnlineStatus($provider = null)
 * @method static \App\Models\Messenger|null getProviderMessenger($provider = null)
 * @method static string|null getProviderAlias()
 * @method static bool providerHasFriends()
 * @method static bool providerHasDevices()
 * @method static bool canMessageProviderFirst($provider = null)
 * @method static bool canFriendProvider($provider = null)
 * @method static bool canSearchProvider($provider = null)
 * @method static GhostUser getGhostProvider()
 * @method static GhostUser getGhostBot()
 * @method static Participant getGhostParticipant(string $threadId)
 * @method static array getSearchableForCurrentProvider()
 * @method static string getApiEndpoint()
 * @method static bool isChannelRoutesEnabled()
 * @method static string|null getProviderDefaultAvatarPath(string $alias)
 * @method static string getDefaultThreadAvatar()
 * @method static string getDefaultNotFoundImage()
 * @method static string getDefaultGhostAvatar()
 * @method static string getDefaultBotAvatar()
 * @method static void reset()
 * @method static void registerProviders(array $providers, bool $overwrite = false)
 * @method static array getMessengerProviders()
 * @method static \App\Messenger getInstance()
 * @method static void flush()
 * @method static int getApiRateLimit()
 * @method static \App\Messenger setApiRateLimit(int $apiRateLimit)
 * @method static int getSearchRateLimit()
 * @method static \App\Messenger setSearchRateLimit(int $searchRateLimit)
 * @method static int getMessageRateLimit()
 * @method static \App\Messenger setMessageRateLimit(int $messageRateLimit)
 * @method static int getAttachmentRateLimit()
 * @method static \App\Messenger setAttachmentRateLimit(int $attachmentRateLimit)
 * @method static \App\Messenger setBroadcastDriver(string $driver)
 * @method static \App\Messenger setVideoDriver(string $driver)
 * @method static \App\Messenger setFriendDriver(string $driver)
 * @method static int getMessageImageSizeLimit()
 * @method static \App\Messenger setMessageImageSizeLimit(int $messageImageSizeLimit)
 * @method static int getMessageDocumentSizeLimit()
 * @method static \App\Messenger setMessageDocumentSizeLimit(int $messageDocumentSizeLimit)
 * @method static int getAvatarSizeLimit()
 * @method static \App\Messenger setAvatarSizeLimit(int $avatarSizeLimit)
 * @method static string getAvatarMimeTypes()
 * @method static \App\Messenger setAvatarMimeTypes(string $avatarMimeTypes)
 * @method static string getMessageDocumentMimeTypes()
 * @method static \App\Messenger setMessageDocumentMimeTypes(string $messageDocumentMimeTypes)
 * @method static string getMessageImageMimeTypes()
 * @method static \App\Messenger setMessageImageMimeTypes(string $messageImageMimeTypes)
 * @method static bool isMessageAudioUploadEnabled()
 * @method static \App\Messenger setMessageAudioUpload(bool $messageAudioUpload)
 * @method static int getMessageAudioSizeLimit()
 * @method static \App\Messenger setMessageAudioSizeLimit(int $messageAudioSizeLimit)
 * @method static string getMessageAudioMimeTypes()
 * @method static \App\Messenger setMessageAudioMimeTypes(string $messageAudioMimeTypes)
 * @method static bool isMessageVideoUploadEnabled()
 * @method static \App\Messenger setMessageVideoUpload(bool $messageVideoUpload)
 * @method static int getMessageVideoSizeLimit()
 * @method static \App\Messenger setMessageVideoSizeLimit(int $messageVideoSizeLimit)
 * @method static string getMessageVideoMimeTypes()
 * @method static \App\Messenger setMessageVideoMimeTypes(string $messageVideoMimeTypes)
 * @method static bool|string getBotSubscriber(string $option)
 * @method static bool|string getCallSubscriber(string $option)
 * @method static bool|string getSystemMessageSubscriber(string $option)
 * @method static \App\Messenger setBotSubscriber(string $option, $value)
 * @method static \App\Messenger setCallSubscriber(string $option, $value)
 * @method static \App\Messenger setSystemMessageSubscriber(string $option, $value)
 * @method static bool shouldUseUuids(?bool $shouldUseUuids = null)
 * @method static bool shouldUseAbsoluteRoutes(bool $shouldUseAbsoluteRoutes = null)
 *
 * @mixin \App\Messenger
 *
 * @see \App\Messenger
 */
class Messenger extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor(): string
    {
        return \App\Messenger::class;
    }
}
